name: "Install and Setup Dependencies"
description: "Install needed dependencies for this repository like Go, Node, Java, Python, etc."

runs:
  using: "composite"
  steps:
    # Install dependencies
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
    # - name: Setup Go with cache
    #   uses: jfrog/.github/actions/install-go-with-cache@main

    - name: Install npm
      uses: actions/setup-node@v4
      with:
        node-version: "16"
    - name: Setup Pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        java-version: "11"
        distribution: "adopt"
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.6

    - name: Install NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: 6.11.0
    - name: Install dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.x'
    
    - name: Setup Python3
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Setup Pipenv
      run: python -m pip install pipenv
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
    - name: Setup Poetry
      run: python -m pip install poetry
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
    - name: Setup Conan
      run: |
        python -m pip install conan
        conan profile detect
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
